# version: "3.9"

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/akantahu/thesis-docker/shared-storage

  deepface-cache: #
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/akantahu/thesis-docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/akantahu/thesis-docker/rekachain-web:/app/rekachain-web
      - /home/akantahu/thesis-docker/shared-storage:/shared-storage
    depends_on:
      - rekachain-web
      - backend-simple-frs
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 1.1.1.1
      
  rekachain-web:
    build:
      context: /rekachain-web
      dockerfile: Dockerfile
    container_name: rekachain-web
    restart: unless-stopped
    tty: true
    working_dir: /app/rekachain-web
    volumes:
      - /home/akantahu/thesis-docker/rekachain-web:/app/rekachain-web
      - /home/akantahu/thesis-docker/shared-storage:/shared-storage
      - /home/akantahu/thesis-docker/.docker/rekachain-web/wait-for-db.sh:/app/rekachain-web/wait-for-db.sh
    networks:
      - app-network
    depends_on:
      - db
    ports:
      # - 8000:8000
      - 5173:5173
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    container_name: v3-wsl-phpmyadmin  
    environment:
      PMA_HOST: db
      # PMA_PORT: 3306
      PMA_USER: akantahu
      PMA_PASSWORD: 12345678
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - app-network
    # volumes:
      # - .docker/phpmyadmin/sessions:/sessions

  db:
    image: mariadb:11.6
    # ports:
    #   - 3306:3306
    container_name: mariadb
    volumes:
      - /home/akantahu/thesis-docker/.docker/db/data:/var/lib/mysql
      - /home/akantahu/thesis-docker/.docker/logs:/var/log/mysql
      - /home/akantahu/thesis-docker/.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - /home/akantahu/thesis-docker/.docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: rekachain_web
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: akantahu
      MYSQL_PASSWORD: 12345678
    networks:
      - app-network

  python-frs:
    build:
      context: /python-frs
      dockerfile: Dockerfile
    container_name: python-frs
    # ports:
    #   - "5000:5000"
    working_dir: /app/python-frs
    volumes:
      - /home/akantahu/thesis-docker/python-frs:/app/python-frs
      - /home/akantahu/thesis-docker/shared-storage:/shared-storage
      - /home/akantahu/thesis-docker/deepface-cache:/root/.deepface
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
