# version: "3.9"

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./shared-storage
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./rekachain-web:/app/rekachain-web
      - ./shared-storage:/shared-storage
    depends_on:
      - rekachain-web
      - backend-simple-frs
    networks:
      - app-network
  rekachain-web:
    build:
      context: ./rekachain-web
      dockerfile: Dockerfile
    container_name: rekachain-web
    restart: unless-stopped
    tty: true
    working_dir: /app/rekachain-web
    volumes:
      - ./rekachain-web:/app/rekachain-web
      - shared-data:/shared-storage
      - .docker/rekachain-web/wait-for-db.sh:/app/rekachain-web/wait-for-db.sh
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - 8000:8000
      - 5173:5173

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      # PMA_PORT: 3306
      PMA_USER: akantahu
      PMA_PASSWORD: 12345678
      PMA_ARBITRARY: 1
    depends_on:
    - db
    networks:
      - app-network
    volumes:
      - .docker/phpmyadmin/sessions:/sessions

  db:
    image: mariadb:11.6
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: rekachain_web
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: akantahu
      MYSQL_PASSWORD: 12345678
    networks:
      - app-network

  backend-simple-frs:
    build:
      context: ./backend-simple-FRS
      dockerfile: Dockerfile
    container_name: backend-simple-frs
    ports:
      - "5000:5000"
    working_dir: /app/backend-simple-FRS
    volumes:
      - ./backend-simple-FRS:/app/backend-simple-FRS
      - shared-data:/shared-storage
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
